// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnSe7TgY5lgf1HYxRtVxWYgLZelWgESQ',
    appId: '1:737869713736:web:28e5e3e4cd6088cd03e37d',
    messagingSenderId: '737869713736',
    projectId: 'expense-tracker-18f6c',
    authDomain: 'expense-tracker-18f6c.firebaseapp.com',
    storageBucket: 'expense-tracker-18f6c.firebasestorage.app',
    measurementId: 'G-00Z4L10WV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKiPsH3h3zH9kru-wtGI9uU9NMkLAcek',
    appId: '1:737869713736:android:722012c460f9af1f03e37d',
    messagingSenderId: '737869713736',
    projectId: 'expense-tracker-18f6c',
    storageBucket: 'expense-tracker-18f6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASINudilfxGd9IvPQKt7ORV6z81ChUTSE',
    appId: '1:737869713736:ios:09ae6a7c0d640b5803e37d',
    messagingSenderId: '737869713736',
    projectId: 'expense-tracker-18f6c',
    storageBucket: 'expense-tracker-18f6c.firebasestorage.app',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASINudilfxGd9IvPQKt7ORV6z81ChUTSE',
    appId: '1:737869713736:ios:09ae6a7c0d640b5803e37d',
    messagingSenderId: '737869713736',
    projectId: 'expense-tracker-18f6c',
    storageBucket: 'expense-tracker-18f6c.firebasestorage.app',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnSe7TgY5lgf1HYxRtVxWYgLZelWgESQ',
    appId: '1:737869713736:web:3452a05bbfa86cf103e37d',
    messagingSenderId: '737869713736',
    projectId: 'expense-tracker-18f6c',
    authDomain: 'expense-tracker-18f6c.firebaseapp.com',
    storageBucket: 'expense-tracker-18f6c.firebasestorage.app',
    measurementId: 'G-8NFRRFXNGL',
  );
}
